version: "3"

services:
  database:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tftordle
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d tftordle -h localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: /tftordle-be
    ports:
      - "3000:3000"
    environment:
      HOST_URL: "http://localhost:3000"
      DB_HOST: "database"
      DB_USER: "postgres"
      DB_PASSWORD: "postgres"
      DB_DATABASE: "tftordle"
      DB_PORT: "5432"
    depends_on:
      database:
        condition: service_healthy

  frontend:
    build: /tftordle-fe
    ports:
      - "80:80"
