FROM node:latest as build

WORKDIR /usr/src/app

COPY ./ /usr/src/app/

RUN npm install

RUN npm run build

FROM nginx:latest

COPY --from=build /usr/src/app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/nginx.conf

EXPOSE 80